### ISSUE TITLE
bug: some elements not in the correct posistion after zooming

### ISSUE THREAD

**Issue by GrayXu** [nizioleque/mouse-pinch-to-zoom#1]
example: 

1. Google something
2. Alt+Scroll to zoom
3. Scroll down
4. And you will find the search box jumps to the center of page.

![1](https://user-images.githubusercontent.com/20384421/167111446-e42f37e3-fcde-483b-8309-aea459ac2dd6.png)

Chrome 101.0.4951.54 Windows 11

Some other sites have similar errors, and I'm wondering if the error is from some small bugs in this plugin, or if those sites need to be targeted and adjusted on a case-by-case basis (*I mean it's a huge amount of work, and doesn't seem like the Chrome implementation.*)

But still the only one I found that works. Appreciate your great work!

**Comment by nizioleque** [comment]
Hi, thank you for the report.
Unfortunately this bug is a side effect of another feature ("Fix for CSS position fixed and sticky"). Without this fix, many elements (especially "dynamically positioned" like right-click context menus) would appear in the wrong place. You can disable this fix in the advanced settings (remember to reload!).

I will try to fix this issue in the future, but I'm afraid those bugs will require patches on a case-by-case basis, as you mentioned.
